version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  redis:
    image: redis:7.0.7-alpine
    restart: always
    ports:
      - "6379:6379"